channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.8
  - pandas=1.2
  - ipykernel
  - plotly=4.14.3
  - ipywidgets[version='>=7.5']
  - matplotlib=3
  - scikit-learn=0.23
  - sympy=1.7
  - scipy=1.6
